spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always
  profiles:
    default: dev

server:
  port: 8090

base-url: /api
welcome-url: /welcome
users-url: /users
login-url: /login

