spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always
  profiles:
    default: dev

server:
  port: 8090

rsa:
  private-key: classpath:certs/private99.pem
  public-key: classpath:certs/public.pem

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

sentry:
  dsn: https://ffb0a3daed8a800961ee3495a9788d38@o4507691214962688.ingest.de.sentry.io/4507691334107216
  traces-sample-rate: 1.0
