spring:
  datasource:
    url: jdbc:h2:mem:myDataBase
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true