spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always
  profiles:
    default: dev

server:
  port: 8090

rsa:
  private-key: classpath:certs/private99.pem
  public-key: classpath:certs/public99.pem

base-url: /api

