spring:
  datasource:
    url: jdbc:h2:mem:myDataBase
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

rsa:
  private-key: classpath:certs/private99.pem
  public-key: classpath:certs/public.pem
